# Generated by Django 4.2.16 on 2026-07-13 18:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('system', 'System Alert'), ('security', 'Security Alert'), ('storage', 'Storage Warning'), ('backup', 'Backup Notification'), ('crm', 'CRM Notification')], default='system', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'site_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
            ],
            options={
                'verbose_name': 'System Backup',
                'verbose_name_plural': 'System Backups',
                'db_table': 'site_system_backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='_smtp_password',
            field=models.CharField(blank=True, db_column='smtp_password', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allowed_origins',
            field=models.TextField(blank=True, help_text='Comma-separated domains for CORS'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='api_token_expiration',
            field=models.PositiveIntegerField(default=30, help_text='In days'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='apple_touch_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apple_icon_settings', to='media_library.mediafile'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_colors',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'primary': '#ff0000', 'secondary': '#00ff00'}"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loading_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loading_logo_settings', to='media_library.mediafile'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_login_attempts',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='open_graph_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='open_graph_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='password_policy',
            field=models.CharField(default='strong', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='session_timeout',
            field=models.PositiveIntegerField(default=1440, help_text='In minutes'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_encryption',
            field=models.CharField(choices=[('none', 'None'), ('ssl', 'SSL'), ('tls', 'TLS')], default='tls', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_provider',
            field=models.CharField(blank=True, default='Custom', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_sender_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_sender_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_card_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary_large_image', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='two_factor_auth_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'X (Twitter)'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('behance', 'Behance'), ('dribbble', 'Dribbble'), ('medium', 'Medium')], max_length=50),
        ),
    ]
