# Generated by Django 4.2.16 on 2026-07-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_notification_systembackup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
