# Generated by Django 4.2.16 on 2026-07-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_sitesettings_business_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='password_policy',
            field=models.CharField(choices=[('relaxed', 'Relaxed'), ('standard', 'Standard'), ('strict', 'Strict')], default='strict', max_length=255),
        ),
    ]
