# Generated by Django 4.2.16 on 2026-07-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_map_legacy_password_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='lockout_duration',
            field=models.PositiveIntegerField(default=15, help_text='In minutes'),
        ),
    ]
