# Generated by Django 4.2.16 on 2026-07-26 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_sitesettings_lockout_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='api_rate_limit',
            field=models.PositiveIntegerField(default=300, help_text='Maximum API requests per minute per authenticated user.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='login_rate_limit',
            field=models.PositiveIntegerField(default=10, help_text='Maximum login attempts per minute per IP address.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rate_limiting_enabled',
            field=models.BooleanField(default=True, help_text='Enable API rate limiting globally. Disable only for debugging.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='lockout_duration',
            field=models.PositiveIntegerField(default=15, help_text='In minutes', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='max_login_attempts',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='session_timeout',
            field=models.PositiveIntegerField(default=1440, help_text='In minutes. Minimum 1 minute.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
