# Generated by Django 4.2.16 on 2026-08-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_rate_limiting_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_last_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_last_failure_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_last_test_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_last_test_recipient',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_last_test_status',
            field=models.CharField(blank=True, choices=[('not_tested', 'Not Tested'), ('success', 'Operational'), ('error', 'Error')], default='not_tested', max_length=20),
        ),
    ]
