# Generated by Django 4.2.16 on 2026-09-20 10:24

import apps.site_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_email_test_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='core_values',
            field=models.JSONField(blank=True, default=apps.site_settings.models.get_default_core_values, help_text="List of core values [{id: '01', title: '...', desc: '...', icon: 'Award'}]"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='differentiators',
            field=models.JSONField(blank=True, default=apps.site_settings.models.get_default_differentiators, help_text="List of differentiator cards [{stat: '...', title: '...', description: '...', icon: 'Target'}]"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission_statement',
            field=models.TextField(blank=True, default='To help startups, businesses, and organizations build scalable digital products through modern engineering, AI innovation, and world-class technology solutions.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission_title',
            field=models.CharField(blank=True, default='Our Mission', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision_statement',
            field=models.TextField(blank=True, default="To become Africa's most trusted technology partner, connecting world-class engineering talent with organizations building the future."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision_title',
            field=models.CharField(blank=True, default='Our Vision', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='why_choose_us_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='why_choose_us_title',
            field=models.CharField(blank=True, default='What Makes Us Different', max_length=255),
        ),
    ]
