# Generated by Django 6.0.5 on 2026-05-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.PositiveIntegerField(default=0, help_text='Read time in minutes'),
        ),
    ]
