# Generated by Django 4.2.13 on 2026-06-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='blog/images/'),
        ),
    ]
