# Generated by Django 4.2.16 on 2026-07-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtag',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
