# Generated by Django 4.2.16 on 2026-07-05 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text='List of benefit strings.'),
        ),
        migrations.AddField(
            model_name='service',
            name='faqs',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.faq'),
        ),
        migrations.AddField(
            model_name='service',
            name='featured_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_services', to='media_library.mediafile'),
        ),
        migrations.AddField(
            model_name='service',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.industry'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, help_text='Brief summary for cards and banners.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Full HTML or Markdown description.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Draft vs Published status.'),
        ),
    ]
