# Generated by Django 6.0.5 on 2026-05-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='company',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='service_interest',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
