# Generated by Django 4.2.16 on 2026-07-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        ('portfolio', '0002_add_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_media',
            field=models.ForeignKey(blank=True, help_text='Selected image from Media Library', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_projects', to='media_library.mediafile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Legacy/Fallback raw image upload', null=True, upload_to='portfolio/projects/featured/'),
        ),
    ]
