# Generated by Django 4.2.16 on 2026-07-05 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        ('portfolio', '0003_project_featured_media_alter_project_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='media_file',
            field=models.ForeignKey(blank=True, help_text='Selected image from Media Library', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_gallery_images', to='media_library.mediafile'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Legacy/Fallback raw image upload', null=True, upload_to='portfolio/projects/gallery/'),
        ),
    ]
