# Generated by Django 4.2.16 on 2026-09-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projectimage_media_file_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AddField(
            model_name='technology',
            name='category',
            field=models.CharField(default='runtime', help_text='Tech category: runtime (Languages & Runtimes), ai (AI & Machine Learning), cloud (Cloud & Scaling), db (Databases & APIs)', max_length=50),
        ),
        migrations.AddField(
            model_name='technology',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of tech capability for tech stack showcase.'),
        ),
        migrations.AddField(
            model_name='technology',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Icon identifier for frontend rendering (e.g. "nextjs", "go", "python", "pytorch", "kubernetes", "terraform", "postgresql", "flutter")', max_length=100),
        ),
    ]
