# Generated by Django 4.2.16 on 2026-07-02 16:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0002_add_project_tags'),
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('industry', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('company_logo', models.ForeignKey(blank=True, help_text='Company logo from Media Library.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_logos', to='media_library.mediafile')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=255)),
                ('author_position', models.CharField(max_length=255)),
                ('testimonial', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial_authors', to='media_library.mediafile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='testimonials', to='testimonials.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
