# Generated by Django 6.0.5 on 2026-05-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('quote', models.TextField()),
                ('avatar', models.ImageField(blank=True, upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'testimonials',
                'ordering': ['order'],
            },
        ),
    ]
