# Generated by Django 4.2.16 on 2026-07-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='project',
            new_name='related_project',
        ),
    ]
