# Generated by Django 4.2.16 on 2026-07-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_reset', 'Password Reset'), ('profile_update', 'Profile Update'), ('role_change', 'Role Change'), ('status_change', 'Status Change'), ('account_lock', 'Account Lock'), ('account_unlock', 'Account Unlock')], max_length=50),
        ),
    ]
