# Generated by Django 4.2.16 on 2026-06-29 08:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'team_departments',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('position', models.CharField(max_length=200)),
                ('short_bio', models.CharField(blank=True, help_text='Short summary shown in card/grid views (max 500 chars).', max_length=500)),
                ('biography', models.TextField(blank=True, help_text='Full biography shown on the detail/profile page.')),
                ('email', models.EmailField(blank=True, help_text='Public contact email (must be unique if provided).', max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('linkedin_url', models.URLField(blank=True, max_length=300)),
                ('github_url', models.URLField(blank=True, max_length=300)),
                ('twitter_url', models.URLField(blank=True, max_length=300)),
                ('website_url', models.URLField(blank=True, max_length=300)),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Total years of professional experience.')),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of skill strings (e.g. ["Python", "React", "AWS"]).')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured members are promoted on the homepage / hero sections.')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='team.department')),
                ('photo', models.ForeignKey(blank=True, help_text='Select a photo from the Media Library.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_photos', to='media_library.mediafile')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'db_table': 'team_members',
                'ordering': ['display_order', 'last_name', 'first_name'],
            },
        ),
    ]
