# Generated by Django 4.2.16 on 2026-07-13 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_service_benefits_service_faqs_service_featured_media_and_more'),
        ('leads', '0002_alter_lead_options_remove_lead_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='leads', to='services.service'),
        ),
        migrations.AddField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='LeadTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_timeline_actions', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Lead Timeline Event',
                'verbose_name_plural': 'Lead Timeline Events',
                'db_table': 'lead_timeline',
                'ordering': ['-created_at'],
            },
        ),
    ]
