# Generated by Django 4.2.13 on 2026-06-25 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('color', models.CharField(default='#D4A017', max_length=7)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Media Tag',
                'verbose_name_plural': 'Media Tags',
                'db_table': 'media_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='media_library.mediafolder')),
            ],
            options={
                'verbose_name': 'Media Folder',
                'verbose_name_plural': 'Media Folders',
                'db_table': 'media_folders',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(max_length=255, upload_to='media_library/')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 hash of file content', max_length=64)),
                ('is_public', models.BooleanField(default=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='media_library.mediafolder')),
                ('tags', models.ManyToManyField(blank=True, related_name='files', to='media_library.mediatag')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'db_table': 'media_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
